In [1]:
import pandas as pd
import numpy as np
import sqlite3

conn = sqlite3.connect('./oh_plot_tree_data/plot_tree_species.db')

#import libraries and create connection to database

In [16]:
red_maple = pd.read_sql_query("SELECT * FROM 'Red Maple'", conn)

In [17]:
red_maple

,index,plot_sequence_number,measurement_year,measurement_month,species_code,latitude,longitude,avg_height,avg_diameter
0,0,275621949489998,40,10.0,316,34.411236,-94.759239,34.600000,5.329000
1,1,55945681010538,44,11.0,316,41.982132,-71.692322,57.571429,6.322222
2,2,3204395010661,17,10.0,316,38.310001,-88.750000,NaN,7.408333
3,3,14262983020004,10,3.0,316,38.928974,-75.729942,NaN,NaN
4,4,162404716010854,40,4.0,316,34.580002,-94.500000,NaN,1.000000
5,5,221354486010661,44,9.0,316,41.497597,-71.516068,NaN,NaN
6,6,3164634010661,17,2.0,316,38.349998,-88.480003,NaN,6.391667
7,7,3147141010661,17,12.0,316,38.169998,-90.209999,NaN,1.366667
8,8,145006201010661,10,6.0,316,38.815956,-75.582359,62.238095,9.865217
9,9,168931291010661,10,6.0,316,38.569618,-75.389053,NaN,NaN
10,10,157325702010478,40,2.0,316,34.241100,-94.763573,44.625000,5.270000
11,11,162407083010854,40,3.0,316,33.939999,-94.809998,39.000000,2.700000
12,12,15651483020004,17,9.0,316,37.379738,-88.947197,56.066667,9.516667
13,13,3166756010661,17,7.0,316,37.660000,-89.070000,NaN,10.400000
14,14,10184621010661,44,6.0,316,41.805660,-71.721733,NaN,8.579487
15,15,74340611010538,44,12.0,316,41.510036,-71.647774,50.071429,8.406250
16,16,304032806489998,10,3.0,316,38.608456,-75.505058,NaN,NaN
17,17,70014750010661,17,6.0,316,38.342365,-88.486916,61.181818,8.346667
18,18,102163777010661,17,11.0,316,37.119091,-89.213219,69.714286,8.868750
19,19,9192547010661,10,9.0,316,38.527889,-75.471863,NaN,8.419231
20,20,9195013010661,10,7.0,316,38.583450,-75.388527,NaN,7.612500
21,21,10186206010661,44,9.0,316,41.444538,-71.610619,NaN,7.550000
22,22,375816014489998,10,5.0,316,39.150772,-75.686852,81.000000,13.811111
23,23,10181437010661,44,7.0,316,41.527882,-71.443947,NaN,8.995652
24,24,60137359010538,10,2.0,316,38.474220,-75.287598,48.142857,4.773913
25,25,102139692010661,17,8.0,316,37.379738,-88.947197,60.750000,8.838889
26,26,3135493010661,17,7.0,316,37.430000,-88.980003,NaN,13.000000
27,27,10180283010661,44,7.0,316,41.750099,-71.721733,NaN,8.180000
28,28,3247394010661,17,4.0,316,39.360001,-88.830002,NaN,22.906452
29,29,74339411010538,44,12.0,316,41.822720,-71.628975,67.000000,12.080000
...,...,...,...,...,...,...,...,...,...
222961,222961,90672894010661,55,9.0,316,45.868587,-88.789032,35.000000,5.200000
222962,222962,24303219010661,55,3.0,316,45.669998,-88.779999,NaN,13.500000
222963,222963,24069892010661,55,8.0,316,46.380001,-91.879997,NaN,5.000000
222964,222964,64317825010661,55,1.0,316,43.837715,-88.145714,86.000000,18.100000
222965,222965,24084754010661,55,8.0,316,45.849998,-88.730003,NaN,2.200000
222966,222966,90684422010661,55,11.0,316,43.556999,-88.128654,57.000000,9.500000
222967,222967,102138149010661,55,1.0,316,45.470261,-88.449097,71.000000,10.400000
222968,222968,24197759010661,55,11.0,316,46.070000,-91.860001,NaN,10.200000
222969,222969,24034256010661,55,11.0,316,46.090000,-90.669998,NaN,17.100000
222970,222970,24159173010661,55,12.0,316,45.470001,-90.139999,NaN,8.800000
222971,222971,24435551010661,55,5.0,316,45.900002,-90.199997,NaN,4.100000
222972,222972,24414748010661,55,7.0,316,45.619999,-89.089996,NaN,1.700000
222973,222973,107111976010661,55,10.0,316,46.042889,-90.281136,49.000000,5.200000
222974,222974,249881976489998,55,7.0,316,45.334270,-88.916779,45.000000,5.100000
222975,222975,306349794489998,55,4.0,316,44.521782,-91.540924,71.000000,7.900000
222976,222976,24063281010661,55,7.0,316,43.040001,-89.089996,NaN,16.299999
222977,222977,24191420010661,55,7.0,316,46.180000,-89.349998,NaN,1.700000
222978,222978,24198825010661,55,7.0,316,45.980000,-91.750000,NaN,3.100000
222979,222979,168271117020004,55,2.0,316,45.128922,-91.547760,43.000000,6.000000
222980,222980,373752795489998,55,5.0,316,43.932625,-90.212952,82.000000,19.500000
222981,222981,24195785010661,55,8.0,316,46.099998,-89.180000,NaN,8.300000
222982,222982,24355879010661,55,11.0,316,45.270000,-88.750000,NaN,1.900000
222983,222983,102133136010661,55,10.0,316,44.613052,-90.556122,NaN,1.100000
222984,222984,69822288010661,55,5.0,316,45.769108,-89.652916,NaN,1.000000
222985,222985,168272611020004,55,7.0,316,45.625736,-92.875870,34.000000,5.600000
222986,222986,24510378010661,55,11.0,316,43.099998,-88.150002,NaN,32.500000
222987,222987,107109051010661,55,8.0,316,45.226864,-92.203384,NaN,4.000000
222988,222988,220875321010661,55,6.0,316,46.388226,-90.432884,35.000000,5.000000
222989,222989,24304657010661,55,11.0,316,45.520000,-88.870003,NaN,1.600000
222990,222990,24218462010661,55,1.0,316,46.459999,-90.730003,NaN,4.300000

In [21]:
def get_avg(df):
    
#This function goes through dataframe and averages 
#over the diameters and heights of 
#all the trees of each species for each year 
#The name of the species can be found in appendix F of the pdf file in the main folder

    measurement_year = df['measurement_year']
    species_code = hocking['species_code']
    avg_dia = pd.DataFrame()
    avg_hei = pd.DataFrame()
    years = measurement_year.sort_values().unique()
    species = species_code.dropna().sort_values().unique()
    avg_dia['species_code'] = species
    avg_hei['species_code'] = species
    
    for i in years:
        temp_avg_array_dia = np.empty(len(species))
        temp_avg_array_hei = np.empty(len(species))
        for j in species:
            temp_dia = df.loc[(df.species_code == j) & (df.measurement_year ==i)].mean().current_diameter
            temp_avg_array_dia[np.where(species == j)] = temp_dia
            temp_hei = df.loc[(df.species_code == j) & (df.measurement_year ==i)].mean().total_height
            temp_avg_array_hei[np.where(species == j)] = temp_hei
        avg_dia[i] = temp_avg_array_dia
        avg_hei[i] = temp_avg_array_hei
    
    return avg_dia, avg_hei

In [22]:
avg_dia, avg_hei = get_avg(hocking)

In [23]:
avg_dia.head()

,species_code,1990,1991,2001,2002,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,97.0,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,...,6.800000,NaN,NaN,NaN,NaN,7.300000,NaN,NaN,NaN,NaN
1,126.0,NaN,7.983019,10.333333,NaN,14.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.800000,NaN,NaN,NaN,NaN,NaN
2,129.0,NaN,11.546875,NaN,NaN,12.356250,NaN,9.20,NaN,NaN,...,NaN,NaN,10.4250,NaN,13.864286,NaN,NaN,9.042857,NaN,NaN
3,130.0,NaN,5.840000,NaN,NaN,10.042857,NaN,NaN,NaN,NaN,...,9.983333,NaN,NaN,NaN,NaN,10.760000,NaN,NaN,NaN,NaN
4,132.0,NaN,9.168889,11.180000,9.78,NaN,16.700001,10.25,NaN,10.36,...,13.400000,NaN,12.4375,10.966667,14.300000,17.799999,13.9,12.000000,14.0,NaN