In [73]:
import pandas as pd
import numpy as np

In [4]:
hocking = pd.read_csv('./oh_plot_tree_data/Hocking_county.csv')

In [6]:
hocking.head()

,Unnamed: 0,plot_sequence_number,plot_state_code,plot_county_code,measurement_year,latitude,longitude,tree_sequence_number,species_code,current_diameter
0,0,19132805010661,39,73,1991,39.388962,-82.638779,1.913281e+13,802.0,31.799999
1,1,19131079010661,39,73,1991,39.416729,-82.638779,1.913108e+13,621.0,10.300000
2,2,19131243010661,39,73,1991,39.527851,-82.360992,1.913125e+13,314.0,8.100000
3,3,19132689010661,39,73,1991,39.361179,-82.583221,1.913269e+13,491.0,1.200000
4,4,19133212010661,39,73,1991,39.527851,-82.249870,1.913325e+13,621.0,2.300000

In [14]:
hocking.groupby('species_code').count()

,Unnamed: 0,plot_sequence_number,plot_state_code,plot_county_code,measurement_year,latitude,longitude,tree_sequence_number,current_diameter
species_code,,,,,,,,,
97.0,3,3,3,3,3,3,3,3,3
126.0,62,62,62,62,62,62,62,62,59
129.0,94,94,94,94,94,94,94,94,92
130.0,35,35,35,35,35,35,35,35,33
132.0,109,109,109,109,109,109,109,109,95
261.0,67,67,67,67,67,67,67,67,63
314.0,4,4,4,4,4,4,4,4,4
316.0,766,766,766,766,766,766,766,766,726
318.0,375,375,375,375,375,375,375,375,352
331.0,1,1,1,1,1,1,1,1,1
332.0,23,23,23,23,23,23,23,23,23
341.0,27,27,27,27,27,27,27,27,25
356.0,16,16,16,16,16,16,16,16,11
367.0,17,17,17,17,17,17,17,17,15
372.0,65,65,65,65,65,65,65,65,55
373.0,49,49,49,49,49,49,49,49,43
391.0,108,108,108,108,108,108,108,108,96
400.0,62,62,62,62,62,62,62,62,62
402.0,26,26,26,26,26,26,26,26,24
403.0,91,91,91,91,91,91,91,91,80
407.0,52,52,52,52,52,52,52,52,51
409.0,50,50,50,50,50,50,50,50,48
462.0,5,5,5,5,5,5,5,5,5
471.0,20,20,20,20,20,20,20,20,19
491.0,204,204,204,204,204,204,204,204,194
500.0,22,22,22,22,22,22,22,22,19
521.0,7,7,7,7,7,7,7,7,5
531.0,246,246,246,246,246,246,246,246,228
541.0,103,103,103,103,103,103,103,103,96
543.0,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
621.0,525,525,525,525,525,525,525,525,505
660.0,1,1,1,1,1,1,1,1,1
663.0,2,2,2,2,2,2,2,2,1
682.0,3,3,3,3,3,3,3,3,3
693.0,90,90,90,90,90,90,90,90,84
701.0,35,35,35,35,35,35,35,35,31
711.0,165,165,165,165,165,165,165,165,149
731.0,76,76,76,76,76,76,76,76,72
742.0,12,12,12,12,12,12,12,12,12
743.0,204,204,204,204,204,204,204,204,167
746.0,10,10,10,10,10,10,10,10,10
760.0,2,2,2,2,2,2,2,2,2
762.0,221,221,221,221,221,221,221,221,202
763.0,2,2,2,2,2,2,2,2,1
802.0,274,274,274,274,274,274,274,274,265
806.0,55,55,55,55,55,55,55,55,54
817.0,12,12,12,12,12,12,12,12,10
830.0,1,1,1,1,1,1,1,1,1
832.0,234,234,234,234,234,234,234,234,224
833.0,199,199,199,199,199,199,199,199,191
837.0,121,121,121,121,121,121,121,121,114
901.0,27,27,27,27,27,27,27,27,26
922.0,6,6,6,6,6,6,6,6,6
931.0,197,197,197,197,197,197,197,197,176
950.0,1,1,1,1,1,1,1,1,1
951.0,7,7,7,7,7,7,7,7,7
970.0,10,10,10,10,10,10,10,10,10
972.0,225,225,225,225,225,225,225,225,209
975.0,91,91,91,91,91,91,91,91,84
999.0,1,1,1,1,1,1,1,1,1

In [94]:
measurement_year = hocking['measurement_year']
species = hocking.species_code.sort_values().unique()
year = measurement_year.sort_values().unique()
hocking.loc[(hocking.measurement_year == 1991) & (hocking.species_code == 126)].mean()

Unnamed: 0              3.117377e+03
plot_sequence_number    1.913233e+13
plot_state_code         3.900000e+01
plot_county_code        7.300000e+01
measurement_year        1.991000e+03
latitude                3.947333e+01
longitude              -8.253238e+01
tree_sequence_number    1.913235e+13
species_code            1.260000e+02
current_diameter        7.983019e+00
dtype: float64

In [32]:
species.dropna().sort_values().unique()

array([ 97., 126., 129., 130., 132., 261., 314., 316., 318., 331., 332.,
       341., 356., 367., 372., 373., 391., 400., 402., 403., 407., 409.,
       462., 471., 491., 500., 521., 531., 541., 543., 544., 552., 601.,
       602., 611., 621., 660., 663., 682., 693., 701., 711., 731., 742.,
       743., 746., 760., 762., 763., 802., 806., 817., 830., 832., 833.,
       837., 901., 922., 931., 950., 951., 970., 972., 975., 999.])

In [84]:
def get_avg(df):
    
    measurement_year = df['measurement_year']
    species_code = hocking['species_code']
    avg = pd.DataFrame()
    years = measurement_year.sort_values().unique()
    species = species_code.dropna().sort_values().unique()
    avg['species_code'] = species
    
    for i in years:
        temp_avg_array = np.empty(len(species))
        for j in species:
            temp = df.loc[(df.species_code == j) & (df.measurement_year ==i)].mean().current_diameter
            temp_avg_array[np.where(species == j)] = temp
        avg[i] = temp_avg_array
    
    return avg

In [85]:
get_avg(hocking)

,species_code,1990,1991,2001,2002,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,97.0,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,...,6.800000,NaN,NaN,NaN,NaN,7.300000,NaN,NaN,NaN,NaN
1,126.0,NaN,7.983019,10.333333,NaN,14.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.800000,NaN,NaN,NaN,NaN,NaN
2,129.0,NaN,11.546875,NaN,NaN,12.356250,NaN,9.200000,NaN,NaN,...,NaN,NaN,10.425000,NaN,13.864286,NaN,NaN,9.042857,NaN,NaN
3,130.0,NaN,5.840000,NaN,NaN,10.042857,NaN,NaN,NaN,NaN,...,9.983333,NaN,NaN,NaN,NaN,10.760000,NaN,NaN,NaN,NaN
4,132.0,NaN,9.168889,11.180000,9.780000,NaN,16.700001,10.250000,NaN,10.360000,...,13.400000,NaN,12.437500,10.966667,14.300000,17.799999,13.900000,12.000000,14.000000,NaN
5,261.0,NaN,13.316667,11.666667,NaN,11.550000,NaN,11.475000,13.133333,NaN,...,NaN,NaN,14.477778,NaN,NaN,11.350000,16.066667,7.700000,NaN,15.925000
6,314.0,NaN,10.375000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,316.0,NaN,9.314136,9.786486,7.766667,9.219048,7.075000,8.929412,10.809677,9.100000,...,9.289655,8.814286,10.571429,10.550000,9.751724,8.653521,8.306250,9.641379,10.572222,11.571429
8,318.0,NaN,8.874757,8.252381,8.312500,12.016667,8.080000,6.850000,6.878572,8.700000,...,7.955556,3.742857,8.842857,8.200000,9.156250,7.991667,9.190909,4.236364,5.100000,8.900000
9,331.0,NaN,5.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,332.0,NaN,6.800000,NaN,NaN,NaN,NaN,8.666667,NaN,12.900000,...,NaN,9.200000,5.200000,NaN,10.500000,6.000000,NaN,9.733333,NaN,6.100000
11,341.0,NaN,NaN,3.900000,6.025000,NaN,NaN,NaN,5.500000,6.383333,...,NaN,NaN,5.800000,NaN,6.000000,NaN,NaN,NaN,6.075000,NaN
12,356.0,NaN,NaN,1.033333,NaN,NaN,NaN,NaN,NaN,1.000000,...,NaN,NaN,1.433333,NaN,1.000000,NaN,NaN,NaN,1.700000,NaN
13,367.0,NaN,1.000000,1.633333,NaN,NaN,NaN,NaN,1.675000,NaN,...,NaN,NaN,1.875000,NaN,NaN,NaN,NaN,NaN,NaN,2.233333
14,372.0,NaN,9.230000,1.780000,NaN,8.485714,13.000000,6.400000,2.175000,NaN,...,13.200000,NaN,3.233333,NaN,7.133333,12.800000,NaN,7.450000,3.750000,3.875000
15,373.0,NaN,20.600000,8.820000,NaN,NaN,NaN,NaN,7.481818,NaN,...,NaN,NaN,7.861538,NaN,NaN,NaN,NaN,5.200000,NaN,7.625000
16,391.0,NaN,2.138462,3.250000,1.266667,NaN,1.500000,1.200000,5.700000,1.250000,...,1.614286,NaN,6.100000,NaN,1.166667,NaN,1.933333,1.033333,NaN,4.080000
17,400.0,NaN,9.508065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,402.0,NaN,1.000000,NaN,5.700000,6.700000,NaN,11.400000,NaN,7.933333,...,8.900000,6.300000,11.800000,NaN,8.300000,9.700000,9.300000,7.900000,NaN,NaN
19,403.0,NaN,NaN,9.500000,8.240000,10.860000,8.730000,12.171429,7.725000,8.125000,...,12.300000,7.116667,8.600000,NaN,10.085714,11.460000,NaN,10.783334,8.600000,NaN
20,407.0,NaN,NaN,8.900000,9.100000,11.166667,14.600000,11.200000,9.600000,10.850000,...,NaN,11.020000,5.650000,NaN,12.140000,10.450000,NaN,9.214286,1.300000,10.500000
21,409.0,NaN,NaN,1.950000,NaN,10.950000,8.825000,12.160000,2.150000,NaN,...,13.960000,6.733333,4.800000,NaN,12.325000,11.000000,NaN,14.400000,NaN,3.700000
22,462.0,NaN,9.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,471.0,NaN,4.880000,NaN,7.500000,1.500000,NaN,5.600000,NaN,8.400000,...,NaN,2.000000,NaN,NaN,3.460000,NaN,NaN,2.200000,NaN,NaN
24,491.0,NaN,2.378519,1.533333,5.825000,3.700000,4.400000,4.680000,1.400000,5.900000,...,3.650000,3.200000,3.900000,6.100000,2.920000,3.500000,5.100000,3.500000,2.000000,NaN
25,500.0,NaN,1.880000,NaN,NaN,NaN,NaN,3.175000,NaN,NaN,...,NaN,1.500000,6.000000,NaN,1.400000,NaN,5.800000,1.500000,NaN,NaN
26,521.0,NaN,6.550000,NaN,5.600000,NaN,NaN,NaN,NaN,5.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,531.0,NaN,11.814286,10.880000,4.472727,7.150000,6.350000,5.900000,11.527273,6.150000,...,5.741667,6.600000,9.187500,NaN,6.237500,5.763636,5.262500,5.942857,9.885714,8.500000
28,541.0,NaN,7.396429,11.900000,8.700000,4.500000,7.550000,7.300000,13.266667,10.333333,...,7.854545,5.400000,8.200000,6.800000,9.785714,11.820000,7.500000,7.266666,5.800000,NaN
29,543.0,NaN,9.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,621.0,NaN,10.312621,8.517857,10.200000,10.879167,10.333333,13.420000,9.860000,11.380000,...,12.863636,14.333334,11.522222,NaN,13.250000,11.350000,12.661538,15.333333,9.888462,22.849999
36,660.0,NaN,3.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,663.0,NaN,NaN,NaN,NaN,NaN,2.200000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,682.0,NaN,NaN,NaN,NaN,6.700000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.200000,NaN,NaN,NaN,NaN,NaN
39,693.0,NaN,5.652941,3.525000,8.900000,4.466667,5.425000,6.000000,5.700000,NaN,...,NaN,3.900000,4.210000,NaN,4.733333,6.866667,NaN,5.383333,1.050000,NaN
40,701.0,NaN,2.636364,NaN,NaN,NaN,6.400000,4.750000,NaN,NaN,...,2.966667,NaN,2.800000,NaN,1.850000,3.700000,1.500000,4.975000,NaN,NaN
41,711.0,NaN,5.741463,4.293333,NaN,5.650000,NaN,6.100000,5.244444,NaN,...,5.471429,NaN,5.652632,NaN,9.060000,5.781818,6.500000,NaN,6.390000,3.920000
42,731.0,NaN,12.034375,25.400000,1.100000,NaN,NaN,16.681818,17.000000,25.650001,...,14.300000,NaN,18.912500,NaN,11.866666,NaN,17.044444,NaN,NaN,22.200001
43,742.0,NaN,11.720000,3.600000,NaN,NaN,NaN,12.800000,NaN,NaN,...,13.250000,NaN,NaN,NaN,NaN,NaN,13.950000,NaN,NaN,NaN
44,743.0,NaN,10.023913,4.568421,9.828571,1.600000,9.875000,12.483333,6.685000,8.700000,...,13.455556,8.850000,7.429412,NaN,5.800000,10.050000,13.922222,7.800000,9.500000,NaN
45,746.0,NaN,12.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,760.0,NaN,5.150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,762.0,NaN,8.618605,7.629412,9.560000,8.563636,11.800000,8.260000,8.762500,9.380000,...,6.345455,12.825000,8.186364,11.750000,10.266667,7.171429,NaN,11.483333,7.360000,16.966667
48,763.0,NaN,NaN,NaN,NaN,9.200000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,802.0,NaN,11.863810,10.528572,10.761538,12.580000,8.575000,11.904167,12.216667,10.750000,...,9.972727,14.690909,13.386667,7.200000,15.980000,14.530000,5.650000,13.913636,3.300000,NaN
50,806.0,NaN,10.411111,14.533333,15.500000,13.050000,8.780000,14.700000,16.033333,NaN,...,NaN,14.400000,17.450000,NaN,5.300000,10.980000,NaN,15.500000,NaN,NaN
51,817.0,NaN,9.600000,NaN,NaN,NaN,8.900000,NaN,NaN,NaN,...,11.066666,NaN,NaN,NaN,NaN,14.300000,NaN,NaN,NaN,NaN
52,830.0,NaN,5.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,832.0,NaN,12.075439,13.807692,NaN,12.400000,8.788889,16.680000,14.723077,NaN,...,NaN,15.214286,16.000000,NaN,12.030435,14.273684,NaN,17.660000,20.000000,NaN
54,833.0,NaN,11.579104,3.650000,15.062500,6.000000,12.720000,15.625000,4.600000,15.214286,...,14.418182,12.928571,12.700000,NaN,13.705263,17.657143,14.650000,11.977778,6.366667,NaN
55,837.0,NaN,10.572000,3.550000,9.957143,NaN,9.000000,13.971429,2.700000,10.500000,...,6.200000,14.633333,4.000000,9.350000,13.850000,11.457143,6.550000,14.466667,5.400000,NaN
56,901.0,NaN,7.618182,NaN,11.600000,NaN,5.600000,5.800000,NaN,13.750000,...,5.800000,6.300000,NaN,NaN,14.150000,5.900000,6.000000,6.400000,NaN,NaN
57,922.0,NaN,1.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,931.0,NaN,6.990164,8.611111,7.733333,6.940000,6.787500,9.700000,7.650000,7.073333,...,7.237500,6.660000,13.675000,6.488889,6.178571,6.890909,9.900000,6.600000,17.766667,3.600000
59,950.0,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,951.0,NaN,4.825000,NaN,NaN,NaN,8.800000,NaN,NaN,NaN,...,8.900000,NaN,NaN,NaN,NaN,NaN,9.000000,NaN,NaN,NaN
61,970.0,NaN,4.460000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,972.0,NaN,6.918889,NaN,6.010000,7.100000,6.213333,7.056250,5.300000,6.400000,...,7.189474,6.300000,6.977778,2.700000,7.716667,6.400000,7.769231,5.020000,9.000000,5.500000
63,975.0,NaN,6.975000,5.600000,6.650000,6.650000,10.166667,5.233333,5.800000,7.633333,...,7.412500,7.733333,4.540000,NaN,5.827273,5.650000,7.557143,8.433333,6.700000,NaN
64,999.0,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN